
theme: jekyll-agency

url    : "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title      : BL Monitor and Control
email      : david.mcginnis@bl-mc.se #this is also the email contact forms will go to
description: "BL Monitor and Control"
author     : David McGinnis
logo:     #optional, defaults to site title
  path: assets/img/clients/blmc-logo.png
  height: 60 #height in px, defaults to 52px

locale: "en-US" # See available languages in _data/sitetext.yml

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
formspree_form_path: "f/mknavpnr"